# Node.js

strategy:
  matrix:
    linux-node-latest:
      imageName: 'ubuntu-latest'
      nodeVersion: '>=12.x'

trigger:
- develop

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run test
    echo $(API_ENDPOINT)
    sed -i 's/http:\/\/localhost:8080/$(API_ENDPOINT)' next.config.js
    npm run build
    npm run export
  displayName: 'Install and build'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'out'
    artifact: 'OntologyVisualisation'
    publishLocation: 'pipeline'